vpc_id = "vpc-0fcbf944165ec4597"
cidr_ipv4 = "0.0.0.0/0"
security_group_name = "splunk-dev-sg"
security_group_description = "Splunk Development Security Group" 
ip_protocol = "tcp"
management_port = 8089
receiving_port = 9997
web_interface_port = 8000
api_port = 443
role_name = "splunk-dev-role"
profile_name = "splunk-dev-profile"
tags = {
  Environment = "Development"
  Project = "Splunk"
  Team = "DevOps"
  CreatedBy = "Terraform"
  CreatedAt = "2026-07-18"
  UpdatedAt = "2026-07-18"
}